/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215715;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CardTest {
    @Test
    void getIntegerNumberTest(){
        Card card = new Card("J","ハート");
        assertEquals(card.getIntegerNumber(), 10);
    }
    
}
