/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215715;

class App{
    /**
     * ゲームを動かすmainメソッド
     * @param args
     */
    public static void main(String[] args) {
        GemeMaster master = new GemeMaster();
        master.start();
    
    }
}

